### ISSUE TITLE
Quark analysis failing

### ISSUE THREAD

**Issue by amsharma44** [quark-engine/quark-engine#111]
Environment:
Windows 10 20H2
Python 3.7.7
Quark 21.01.5

Apk used:
https://apkpure.com/instagram/com.instagram.android/download?from=details

Console output:
```
PS C:\Users\User\Desktop\apk-test> quark -a instagram.apk -o result.json

    ________                      __
    \_____  \  __ _______ _______|  | __
     /  / \  \|  |  \__  \_  __ \  |/ /
    /   \_/.  \  |  // __ \|  | \/    <
    \_____\ \_/____/(____  /__|  |__|_ \
           \__>          \/           \/ v21.01.5

                An Obfuscation-Neglect Android Malware Scoring System

 36%|████████████████████████████████████████████████████▌                                                                                              | 25/70 [00:09<00:24,  1.82it/s]--- Logging error ---
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "c:\users\user\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u3002' in position 140: character maps to <undefined>
Call stack:
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\quark.exe\__main__.py", line 7, in <module>
    sys.exit(entry_point())
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\quark\cli.py", line 143, in entry_point
    data.run(rule_checker)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\quark\Objects\quark.py", line 284, in run
    if self.check_parameter(parent_function, first_wrapper, second_wrapper):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\quark\Objects\quark.py", line 177, in check_parameter
    pyeval.eval[instruction[0]](instruction)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\quark\Evaluator\pyeval.py", line 32, in warp
    log.info(f"{func.__name__} with args-> {args}")
Message: "CONST_STRING with args-> (<quark.Evaluator.pyeval.PyEval object at 0x000001FC817B2648>, ['const-string', 'v0', '。#ig'])"
Arguments: ()
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 [00:22<00:00,  3.09it/s]
```

Quark logs:
https://anonfiles.com/j2J9NaC6p4/2021-01-26.quark_log

**Comment by Surendrajat** [comment]
Potential cause: https://stackoverflow.com/a/42495690

**Comment by haeter525** [comment]
Since #230 has solved this by removing the problematic code from the release, I will close the issue lately.
Thank you for reporting this!
