### ISSUE TITLE
Deleting rules crashes Quark in Windows 10

### ISSUE THREAD

**Issue by haeter525** [quark-engine/quark-engine#136]
**Describe the bug**
When I use Quark for the first time in a day, an access denied message pops up and crashes it.

**To Reproduce**
1. Make sure today is not the date stored at `~/.quark-engine/.up_to_date.quark`
2. Open a terminal
3. Run `quark` with/without arguments. e.g. `quark --help`

**Expected behavior**
Suppress the error or prompt it to the user.

**Screenshots**
```
PS C:\Users\cinde> quark --help

    ________                      __
    \_____  \  __ _______ _______|  | __
     /  / \  \|  |  \__  \_  __ \  |/ /
    /   \_/.  \  |  // __ \|  | \/    <
    \_____\ \_/____/(____  /__|  |__|_ \
           \__>          \/           \/ v21.02.1

                An Obfuscation-Neglect Android Malware Scoring System

Traceback (most recent call last):
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\quark\freshquark.py", line 59, in download
    git.Repo.clone_from(url=SOURCE, to_path=DIR_PATH)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\git\repo\base.py", line 1032, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\git\repo\base.py", line 973, in _clone
    finalize_process(proc, stderr=stderr)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\git\util.py", line 329, in finalize_process
    proc.wait(**kwargs)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/quark-engine/quark-rules C:\Users\cinde/.quark-engine/quark-rules
  stderr: 'fatal: destination path 'C:\Users\cinde/.quark-engine/quark-rules' already exists and is not an empty directory.
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cinde\AppData\Local\Programs\Python\Python39\Scripts\quark.exe\__main__.py", line 4, in <module>
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\quark\cli.py", line 20, in <module>
    check_update()
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\quark\freshquark.py", line 46, in check_update
    download()
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\site-packages\quark\freshquark.py", line 68, in download
    shutil.rmtree(DIR_PATH)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\cinde\appdata\local\programs\python\python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] 存取被拒。: 'C:\\Users\\cinde/.quark-engine/quark-rules\\.git\\objects\\pack\\pack-de0af5d4b636a01f23ffe54ad0687b23a5fa2d11.idx'
```

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909
 - Quark: v20.02.1

**Additional context**

**Comment by krnick** [comment]
Hi @haeter525 , thanks for reporting this problem.
It seems that this is caused by deleting git-related files in Windows.

Reference:
https://stackoverflow.com/questions/39566812/python-script-not-deleting-git-files-in-windows
