### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by yashomer1994** [quark-engine/quark-engine#153]
**Calling Graph**
Analysing the apk with graph quark-engine crashed.

**To Reproduce**
1. quark -a sample_apk -s -g 
2. After Creating Call graph
3. python 3.9 traceback error

**Expected behavior**
should produce graph
**Screenshots**

<img width="1430" alt="Screenshot 2021-03-29 at 11 42 52 PM" src="https://user-images.githubusercontent.com/18115054/112880791-8ac65c00-90e8-11eb-8d70-67b3bdaa83c0.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur

**Comment by krnick** [comment]
Hello @yashomer1994 ,

The error showed up is that the `graphviz` is not currently installed on your computer. You can install it through the following command.

```bash
brew install graphviz
```

**Comment by yashomer1994** [comment]
hI @krnick  After Installing the graphviz , getting same the issue

**Comment by fbinliu** [comment]
Same here, with graphviz installed, get the error message as:
`[*] Creating Call Graph...
Traceback (most recent call last):
  File "c:\users\liu\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\liu\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python39\Scripts\quark.exe\__main__.py", line 7, in <module>
  File "C:\Users\liu\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\liu\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\liu\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\liu\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\liu\appdata\local\programs\python\python39\lib\site-packages\quark\cli.py", line 307, in entry_point
    data.show_call_graph()
  File "c:\users\liu\appdata\local\programs\python\python39\lib\site-packages\quark\core\quark.py", line 641, in show_call_graph
    call_graph(call_graph_analysis)
  File "c:\users\liu\appdata\local\programs\python\python39\lib\site-packages\quark\utils\graph.py", line 214, in call_graph
    dot.render(
  File "c:\users\liu\appdata\local\programs\python\python39\lib\site-packages\graphviz\files.py", line 233, in render
    filepath = self.save(filename, directory)
  File "c:\users\liu\appdata\local\programs\python\python39\lib\site-packages\graphviz\files.py", line 195, in save
    with open(filepath, 'w', encoding=self.encoding) as fd:
OSError: [Errno 22] Invalid argument: 'call_graph_image/<init>_getClass_getMethod'`

**Comment by haeter525** [comment]
Hi, @fbinliu and @yashomer1994 ,

Thank you for reporting this!
The call graph requires a working Graphviz in your systems' PATH. Can you kindly check whether running `dot -V` on the command-line prints the version of Graphviz?

**Comment by leeweiche20** [comment]
I got the issue as same as @fbinliu with graphviz version 2.49.1 (20210923.0004).=>Already check by running dot -V command.
Quark version is the latest 21.10.2
And I have tried the solution which mentioned from "v21.8.1 release note" (P.63 10.2.2  #237.)
It still has the same issue.
