### ISSUE TITLE
RecursionError when MAX_SEARCH_LAYER = 3

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#18]
when I execute command as
```
python main.py -a sample/13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk  -r rules/ -e
```
It show error below:

```
Traceback (most recent call last):
  File "main.py", line 172, in find_f_previous_method
    self.find_f_previous_method(item, top)
  File "main.py", line 172, in find_f_previous_method
    self.find_f_previous_method(item, top)
  File "main.py", line 172, in find_f_previous_method
    self.find_f_previous_method(item, top)
  [Previous line repeated 989 more times]
  File "main.py", line 164, in find_f_previous_method
    method_set = self.upperFunc(base[0], base[1])
  File "main.py", line 89, in upperFunc
    method_set = self.find_method(class_name, method_name)
  File "main.py", line 72, in find_method
    if len(list(result)) > 0:
  File "/Users/nick/.local/share/virtualenvs/quark-engine-PkXmWEj6/src/androguard/androguard/core/analysis/analysis.py", line 1776, in find_methods
    classname = bytes(mutf8.MUTF8String.from_str(classname))
  File "/Users/nick/.local/share/virtualenvs/quark-engine-PkXmWEj6/src/androguard/androguard/core/mutf8.py", line 102, in from_str
    c = cls(encode(s))
  File "/Users/nick/.local/share/virtualenvs/quark-engine-PkXmWEj6/src/androguard/androguard/core/mutf8.py", line 64, in encode
    ord_array = [i for i in map(lambda x: ord(x), s)]
  File "/Users/nick/.local/share/virtualenvs/quark-engine-PkXmWEj6/src/androguard/androguard/core/mutf8.py", line 64, in <listcomp>
    ord_array = [i for i in map(lambda x: ord(x), s)]
  File "/Users/nick/.local/share/virtualenvs/quark-engine-PkXmWEj6/src/androguard/androguard/core/mutf8.py", line 64, in <lambda>
    ord_array = [i for i in map(lambda x: ord(x), s)]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I will modify the value to 2 first, and then deal with this issue, please keep this issue until it is resolved

**Comment by sidra-asa** [comment]
Will it solve the problem ?

https://docs.python.org/3/library/sys.html#sys.setrecursionlimit

**Comment by krnick** [comment]
I think it should be part of the my code is not handled well infinite recursion, because `setrecursionlimit` can only limit the maximum value, and it will still raise error.

I'm not sure the reason of this bug for now, the value of the MAX_SEARCH_LAYER need be changed to 2 first, and I will fix it later since it will lead to error in master now.

**Comment by sidra-asa** [comment]
How about just adding important notes? 
Let users understand to adjust MAX_SEARCH_LAYER if they get the same problem, and this problem will be solved soon.
In that way, we don't have to commit a bugfix for a variable adjustment.

**Comment by krnick** [comment]
That sounds great!, then I will close the PR #19, and I will set the MAX_SEARCH_LAYER modifiable in the future.

**Comment by sidra-asa** [comment]
@krnick 
Great work to find the root cause of #18 .
