### ISSUE TITLE
Quark Fails to do analysis on certain APKs

### ISSUE THREAD

**Issue by ajinabraham** [quark-engine/quark-engine#226]
**Describe the bug**

Exception happens here

```
Traceback (most recent call last):                                                                                                                           
  File "/home/seclab/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/quark.py", line 48, in quark_analysis                                       
    data.run(rule_checker)                                                                                                                                   
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Objects/quark.py", line 317, in run                              
    if self.check_parameter(parent_function, first_wrapper, second_wrapper):                                                                                 
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Objects/quark.py", line 190, in check_parameter                  
    pyeval.eval[instruction[0]](instruction)                                                                                                                 
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Evaluator/pyeval.py", line 31, in warp                           
    func(*args, **kwargs)                                                                                                                                    
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Evaluator/pyeval.py", line 336, in AGET_OBJECT                   
    array_obj = self.table_obj.get_obj_list(                                                                                                                 
AttributeError: 'NoneType' object has no attribute 'pop'           
```

Ref: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1774

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sharteeya** [comment]
Hi ajinabraham,
We've received this issue and will investigate it. Thanks for your report!

**Comment by sharteeya** [comment]
Hi ajinabraham,
Since we want to reproduce the error, may we have the APK used in the issue for fixing the bug?
Thanks!

**Comment by ajinabraham** [comment]
I don't have, but requested the issue reporter to provide an APK to replicate this.
