### ISSUE TITLE
Bug with graphviz 0.18. (needed previous version)

### ISSUE THREAD

**Issue by roxax19** [quark-engine/quark-engine#286]
**Describe the bug**
When installing last version of graphviz, one import is missing. I had to install graphicviz 0.16. You might have to update Pipfile.

**To Reproduce**
```
$ git clone https://github.com/quark-engine/quark-engine.git
$ cd quark-engine/
$ pipenv install --skip-lock
$ pipenv shell
$ quark --help
```

**Expected behavior**
I expected it to show quark help.

**Screenshots**
![image](https://user-images.githubusercontent.com/56911452/140887687-600136db-cfb0-48b8-a49b-41400b533f59.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10

**Additional context**
Everything works uninstalling graphviz version 0.18 and installing version 0.16. This is just a reminder that you might have to change Pipfile.

**Comment by mlodic** [comment]
hi guys, I have just encountered the same problem while working on IntelOwl

`[REPORT] Job:1, status:'pending', analyzers:['APKiD_Scan_APK_DEX_JAR', 'Quark_Engine_APK']
Traceback (most recent call last):
  File "/opt/deploy/intel_owl/api_app/core/classes.py", line 123, in start
    _result = self.run()
  File "/opt/deploy/intel_owl/api_app/analyzers_manager/file_analyzers/quark_engine.py", line 12, in run
    from quark.report import Report
  File "/usr/local/lib/python3.9/site-packages/quark/report.py", line 7, in <module>
    from quark.core.quark import Quark
  File "/usr/local/lib/python3.9/site-packages/quark/core/quark.py", line 26, in <module>
    from quark.utils.output import (
  File "/usr/local/lib/python3.9/site-packages/quark/utils/output.py", line 8, in <module>
    from graphviz.dot import Digraph
ImportError: cannot import name 'Digraph' from 'graphviz.dot' (/usr/local/lib/python3.9/site-packages/graphviz/dot.py)`

**Comment by EpicDima** [comment]
Hi everybody. Exactly the same mistake.
`Traceback (most recent call last):
  File "C:\Applications\Python3.9\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Applications\Python3.9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Applications\Python3.9\Scripts\quark.exe\__main__.py", line 4, in <module>
  File "C:\Applications\Python3.9\lib\site-packages\quark\cli.py", line 13, in <module>
    from quark.core.parallelquark import ParallelQuark
  File "C:\Applications\Python3.9\lib\site-packages\quark\core\parallelquark.py", line 8, in <module>
    from quark.core.quark import Quark
  File "C:\Applications\Python3.9\lib\site-packages\quark\core\quark.py", line 26, in <module>
    from quark.utils.output import (
  File "C:\Applications\Python3.9\lib\site-packages\quark\utils\output.py", line 8, in <module>
    from graphviz.dot import Digraph
ImportError: cannot import name 'Digraph' from 'graphviz.dot' (C:\Applications\Python3.9\lib\site-packages\graphviz\dot.py)`

**Comment by mlodic** [comment]
@krnick sorry for the ping, did you have some time to look into this? thank you in advance!

**Comment by haeter525** [comment]
Hi @mlodic , @roxax19 , and @EpicDima 

Sorry for getting back late.
It seems that a file rearrangement on Graphviz 0.18 crashes Quark
We had started investigating this. Thank you all for reporting it.

**Comment by haeter525** [comment]
Thank you @mlodic , @roxax19 , and @EpicDima  for letting us know.
Thank @nplesak  for patching it by #288 . The issue has been fixed by adjusting the import.
We will close it lately and release the latest version as soon as possible. :D
