### ISSUE TITLE
Exception when getting bytecode using Rizin with some apps

### ISSUE THREAD

**Issue by v0lp3** [quark-engine/quark-engine#361]
**Describe the bug**

Using rizin core library:

```
 Traceback (most recent call last):
   File "/opt/bitnami/python/lib/python3.8/multiprocessing/pool.py", line 125, in worker
     result = (True, func(*args, **kwds))
   File "/opt/bitnami/python/lib/python3.8/site-packages/quark/core/parallelquark.py", line 23, in _worker_analysis
     _quark.run(rule_obj)
   File "/opt/bitnami/python/lib/python3.8/site-packages/quark/core/quark.py", line 385, in run
     second_api_list = self.find_api_usage(
   File "/opt/bitnami/python/lib/python3.8/site-packages/quark/core/quark.py", line 327, in find_api_usage
     potential_method_list = [
   File "/opt/bitnami/python/lib/python3.8/site-packages/quark/core/quark.py", line 330, in <listcomp>
     if not next(self.apkinfo.get_method_bytecode(method), None)
   File "/opt/bitnami/python/lib/python3.8/site-packages/quark/core/rzapkinfo.py", line 369, in get_method_bytecode
     yield self._parse_smali(ins["disasm"])
 KeyError: 'disasm'
```

**Comment by haeter525** [comment]
Hi @v0lp3. Thank you for reporting this issue.

Unfortunately, the Rizin core library is not yet ready for actual analysis. For now, it's still under development and may crash easily. But, we are aware of this issue and currently working with the Rizin team to solve it.

I will keep track of this issue and let you know once it's solved. Thank you for reporting it. :D
