### ISSUE TITLE
AttributeError: 'ExternalMethod' object has no attribute 'get_instructions_idx'

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#58]
```
Traceback (most recent call last):
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/cli.py", line 43, in entry_point
    data.run(rule_checker)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/xrule.py", line 300, in run
    if self.check_parameter(common_method, str(pre_0[1]), str(pre_1[1])):
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/xrule.py", line 192, in check_parameter
    for bytecode_obj in self.apkinfo.get_method_bytecode(
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/apkinfo.py", line 87, in get_method_bytecode
    for _, ins in method.get_method().get_instructions_idx():
AttributeError: 'ExternalMethod' object has no attribute 'get_instructions_idx'
```

**Comment by krnick** [comment]
fixed in PR #72 
commit version: 0f0b18fc3e3e17480ceefadf76c3a6462f4f1889
