### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#59]
```
Traceback (most recent call last):
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/cli.py", line 43, in entry_point
    data.run(rule_checker)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/xrule.py", line 300, in run
    if self.check_parameter(common_method, str(pre_0[1]), str(pre_1[1])):
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/xrule.py", line 206, in check_parameter
    pyeval.eval[instruction[0]](instruction)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Evaluator/pyeval.py", line 28, in warp
    func(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Evaluator/pyeval.py", line 251, in CONST_SIXTEEN
    self._assign_value(instruction)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Evaluator/pyeval.py", line 113, in _assign_value
    self.table_obj.insert(index, variable_object)
  File "/home/nick/.local/share/virtualenvs/dangerous-DAW5iOOa/src/quark-engine/quark/Objects/tableobject.py", line 28, in insert
    self.hash_table[index].append(var_obj)
IndexError: list index out of range

```

**Comment by krnick** [comment]
outdated issue
