### ISSUE TITLE
ValueError: Weight calculate failed

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#60]
```
Traceback (most recent call last):
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nick/Desktop/fix_quark/quark-engine/quark/cli.py", line 47, in entry_point
    print_warning(w.calculate())
  File "/Users/nick/Desktop/fix_quark/quark-engine/quark/utils/weight.py", line 48, in calculate
    raise ValueError("Weight calculate failed")
ValueError: Weight calculate failed
```

**Comment by krnick** [comment]
fixed in PR #64
