### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#61]
```
benign_sample/aBsCalendar.Package.apk
  2%|█▏                                                                      | 207/12432 [00:00<00:04, 2621.22it/s]
Traceback (most recent call last):
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/.local/share/virtualenvs/quark-engine-ie8vywLY/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nick/Desktop/fix_quark/quark-engine/quark/cli.py", line 42, in entry_point
    data.run(rule_checker)
  File "/Users/nick/Desktop/fix_quark/quark-engine/quark/Objects/xrule.py", line 309, in run
    if self.check_sequence(common_method, pre_0, pre_1):
  File "/Users/nick/Desktop/fix_quark/quark-engine/quark/Objects/xrule.py", line 179, in check_sequence
    if s_func_val > f_func_val:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by krnick** [comment]
fixed in PR #72
