### ISSUE TITLE
Error occurred while analyzing APK

### ISSUE THREAD

**Issue by pulorsok** [quark-engine/quark-engine#74]
## Description
Error occurred while analyzing APK with the rule.
## Rule content
```
{
    "crime": "Steal Sensitive Information - Get directory info of the SD cards and active network info",
    "x1_permission": [
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.ACCESS_NETWORK_STATE"
    ],
    "x2n3n4_comb": [
        {
            "class": "Landroid/os/Environment",
            "method": "getExternalStorageDirectory"
        },
        {
            "class": "Landroid/net/ConnectivityManager",
            "method": "getActiveNetworkInfo"
        }
    ],
    "yscore": 1,
    "sample": [
        "8acfbc89fa1c760c4cffc6178863e5529d93347c29fa972af7072cb520f49956d55b7f88155671c1d02b54905ec09abd744314d3d4a13c790116583e18f8ebe6",
        "83057e262e794c2c25a59c65d8604885b9dbe9f0880c38518752677508493e21fe63c27708347ae26b76bfed38992f5e0d67da8b273892a52339bba58c661105",
        "014b4e2e536d0f23dfefea6226932e25e76eaf0afa9ee7692f33a0573d6215080a74fabaad35daf0a5b639de554214290c67c802ac5aefd32469042f7ff069bf",
        "3b167d339e5a2027e39a8bfc55b4897ea55312e0ceee6b40903a02e33fecbd10e4c4d43ef1af36a262d01e78f352a3d6a13ecce3ed85d92c815201db8c8a7926",
        "d3623a24648cdadcab189b2c7bec118a2aa63ec5f84ef002eeef44ad5789481c4927bcd76be38bb9920120d6093321b208ea443598edd5c099e3526eefcf1553",
        "c53fe1a510e3003fb4b2743c045efda8b6fdb05e0a05ceb71682080b9476acdf8fec0ae1f8863614400521a743ace0165f4675dbf01e67a88980f321e9683444",
        "f4579b81e8cb6d19a5456bdad9215dfd01d06f24fc45b9474fff9264fcad2feddc9ebba4a02a858b26016faebd28e5623458578d0d24ed0312b75b5c2f516590",
        "94df58b777a539fa0574ab95fd4aa84c65c90977a0b9dfe21bf82544d9dd2a935b813ff2a3f85a9e749293309b6ce5459a3ec423870b737509eab0eaee50a5bf",
        "7deee7286601890557a318986cf9642ed8426131147c4bbde8d5dc7651843a452b1bf3a7aef37048c110d4bee46e76fd4381fa0c29835350d2eeecc05fa60bd7",
        "a13228c19303304968541917fad261b12a00646e49a37eb61c5232f37aa18d91d2af913e66f2785067c9910ae74d51aa0d146523c6c6419bc027ea3dbb81288b",
        "da44a5bd5d6ddb74eff1751dd8ca5bef36c7246c5d166284f374328c7de59bb38977e0c3dee694d619bd8e2b28733cd2045b7d63657076c1d40f4a22343f8d73",
        "fd9a6b886e9e30e90ac364446d98934142c24fef525c445ae5ceee169fb7124a2e17bfdf05177ac5d22b8b944c7aa78f8c181845509708e0f0ea60bb2afdbb43",
        "f8912459991773c9e28061251265aaf908c1edd960fc1c60ae7f141fc2c95eb2a92d3a3891d47f8f2c8d73596626d29c0409ed66a248d6f37c0f623a16d72ed9",
        "73804c796f7ae285fdba3c08d0742c46d758024020cb6614f0a75182c5af3b721a952f6b436226317631b163701f18ed2a8b9df2694a48cf9ee8a321234bacb4",
        "bfbd18234345807597d828842a2f1afadaaca5994337a1f728e3c8736e6ebd787907c9b4e79f43fd95c169351ec5e52f0f45542f6c6a363806d86072b5118e5d",
        "22eb834fc059bd28d112e9eea74c328ed5b7e92059e65c97bdd203a767b51eed640d733682ef8012f1a08c4c4aa60d88bb28d6bb9147cb0d1fbd8e8d599fa041",
        "954f6df7b4ce7f56232a797f7c5bc911a885e526ef92ca072060227ba97280fc4df3b8b605b99cfd24e1415718a630c174607e46ce0112eadf3c88151dd063d8",
        "8612bbb29dc17e584d817b90475b098646ea756f159249af410071c400afa911865cd55cf9cec9f9c0db95b00734885863ab75b1bdfd0e0c73f60b4ac680a483",
        "622821fb262951a2275c20b8fca4eac7c33a8044f0d984e054c3df4acf4da8a914058dc563d96f8f6985b1ac64d8cf93b1c54581e0c909a8011d69c6a740c739",
        "37290d8ba66e0b9f4f7398123c55c5a834e498aa030edb1109cb26b28d85ca2663a876c6cf7510a6ef1174b861905df76617fe7e2c7ab037d0f1539f26cf278e",
        "5751cfdf656f2a5ee021940c5448a77e5b921d1510d2abfa520a57d02c74821e0f5c2e4935bea2554c440072d32fc22bb8317a85dabbbc7c9cca9d1c077793c2",
        "398acd50a4931316d4c5270cfd4fbf56032565a5e4d7265eb29deb1595ccb5cf748667ab39fa02364669d217d871d5308b6a2ad7a9b7fafdda6abe709012d191",
        "2d48ff0bbea51fc61aeb7dbae99f4252f65f8d37b0c949cec40bb788ebc6dfe6f8aa02ee12804d7fb34fdd5def7b28e2de9e66d282acf8f85750edfd3b90e9f2",
        "31c57d6d321a0affff1e2c880c6f5da7d82ab24f0ac2dae6876d17b1f6cc7266a0b046048ee493ffdbc5313ecc05d560b0971dfd0fce9ee36483e18e3e5f1283",
        "934573215329244f74ad7090604d4410732559ea0c981c466d6dee13a2ba6b8533d9d7171af6f5fb7ae07377a495cee8b77e5da1dc1eca68158b3c76395f8b1c",
        "4f60446b97ce44b297e17e334de6d870f5de38ef1d74b2557f3bf684178363d319a5d0e4147f4cc55784e79a8f4eb2de0b6448fc103f5266b8c78b8bd2bca783"
    ]
}
```
## Error message
```
Traceback (most recent call last):
  File "/home/nick/.local/share/virtualenvs/quark-engine-lddAoX17/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/home/nick/.local/share/virtualenvs/quark-engine-lddAoX17/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/quark-engine-lddAoX17/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nick/.local/share/virtualenvs/quark-engine-lddAoX17/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nick/.local/share/virtualenvs/quark-engine-lddAoX17/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nick/quark/quark-engine/quark/cli.py", line 93, in entry_point
    data.run(rule_checker)
  File "/home/nick/quark/quark-engine/quark/Objects/quark.py", line 304, in run
    if self.check_parameter(common_method, str(pre_0[1]), str(pre_1[1])):
  File "/home/nick/quark/quark-engine/quark/Objects/quark.py", line 210, in check_parameter
    pyeval.eval[instruction[0]](instruction)
  File "/home/nick/quark/quark-engine/quark/Evaluator/pyeval.py", line 28, in warp
    func(*args, **kwargs)
  File "/home/nick/quark/quark-engine/quark/Evaluator/pyeval.py", line 251, in CONST_SIXTEEN
    self._assign_value(instruction)
  File "/home/nick/quark/quark-engine/quark/Evaluator/pyeval.py", line 113, in _assign_value
    self.table_obj.insert(index, variable_object)
  File "/home/nick/quark/quark-engine/quark/Objects/tableobject.py", line 28, in insert
    self.hash_table[index].append(var_obj)
IndexError: list index out of range

```

**Comment by sharteeya** [comment]
Since the content in this issue no longer exists in Quark-Engine. This issue will be closed. Thank you for reporting the issue!
