### ISSUE TITLE
call_graph is not work with 0c2494c03f07f891c67bb31390c12c84b0bb5eea132821c0873db7a87f27ccef

### ISSUE THREAD

**Issue by teixeira0xfffff** [quark-engine/quark-engine#81]
Apk: 0c2494c03f07f891c67bb31390c12c84b0bb5eea132821c0873db7a87f27ccef
Download: https://koodous.com/apks?search=0c2494c03f07f891c67bb31390c12c84b0bb5eea132821c0873db7a87f27ccef
More info: https://blog.talosintelligence.com/2020/10/donot-firestarter.html

[*] Creating Call Graph...
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/quark-engine-9yAlCX7e/bin/quark", line 11, in <module>
    load_entry_point('quark-engine', 'console_scripts', 'quark')()
  File "/root/.local/share/virtualenvs/quark-engine-9yAlCX7e/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/quark-engine-9yAlCX7e/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/quark-engine-9yAlCX7e/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/share/virtualenvs/quark-engine-9yAlCX7e/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/quark-engine/quark/cli.py", line 83, in entry_point
    data.show_call_graph()
  File "/root/quark-engine/quark/Objects/quark.py", line 462, in show_call_graph
    call_graph(call_graph_analysis)
  File "/root/quark-engine/quark/utils/graph.py", line 162, in call_graph
    f"{first_wrapper[-1].full_name}",
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/50772593/97715889-af6ac900-1aa1-11eb-8935-e9094023214e.png)

**Comment by 18z** [comment]
Thank you mate! Our monkey army is on the way fixing this problem!!!! :D

**Comment by krnick** [comment]
@teixeira0xfffff  thanks for reporting the issue, monkey is on the way :)

**Comment by krnick** [comment]
Hello @teixeira0xfffff ,

I'm sorry for getting back to you late.

We have solved this issue of generating the call graph, and the latest version is "v21.3.4", you can update quark-engine via `pip install -U quark-engine` to test it.

Also, we have tested this malware example, and the function of the call graph works well.

Thank you 😄

**Comment by teixeira0xfffff** [comment]
it works perfectly! Thank You, awesome project!
![image](https://user-images.githubusercontent.com/50772593/113134698-850b6c00-91f7-11eb-9bc6-fec8f6ce6ae4.png)

**Comment by krnick** [comment]
So glad to hear you like it 😄
