### ISSUE TITLE
Saving report to json

### ISSUE THREAD

**Issue by pokorny-martin** [quark-engine/quark-engine#86]
quark -a to_test\com.fastemulator.gba.apk -r quark\rules --detail -o to_test\quark_gameboy.json

Traceback (most recent call last):
  File "C:\Users\Martin\.virtualenvs\quark-engine-xwtWkN4W\Scripts\quark-script.py", line 33, in <module>
    sys.exit(load_entry_point('quark-engine', 'console_scripts', 'quark')())
  File "C:\Users\Martin\.virtualenvs\quark-engine-xwtWkN4W\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Martin\.virtualenvs\quark-engine-xwtWkN4W\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Martin\.virtualenvs\quark-engine-xwtWkN4W\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Martin\.virtualenvs\quark-engine-xwtWkN4W\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\desktop\android testing\quark-engine\quark\cli.py", line 128, in entry_point
    data.generate_json_report(rule_checker)
  File "d:\desktop\android testing\quark-engine\quark\Objects\quark.py", line 330, in generate_json_report
    for class_name, method_name in self.quark_analysis.level_2_result:
TypeError: cannot unpack non-iterable MethodAnalysis object

**Comment by 18z** [comment]
Thanks for reporting this issue. We'll take a look.

**Comment by sidra-asa** [comment]
@pokorny-martin 
We've done a fix. Would you try with the newer commit and tell us  if any error ?

**Comment by pokorny-martin** [comment]
Works like a charm, thank you.
